nginx:
  image: jiajunx/nginx
  cpu_shares: 100
  mem_limit: 262144000
  ports:
     - "80:80"
  links:
     - "app1:app1"
     - "app2:app2"
     - "app3:app3"
app1:
  image: jiajunx/tinyurl
  cpu_shares: 100
  mem_limit: 262144000
  ports:
     - "3000"
  links:
     - "cache:redis"

app2:
  image: jiajunx/tinyurl
  cpu_shares: 100
  mem_limit: 262144000
  ports:
     - "3000"
  links:
     - "cache:redis"

app3:
  image: jiajunx/tinyurl
  cpu_shares: 100
  mem_limit: 262144000
  ports:
     - "3000"
  links:
     - "cache:redis"

cache:
  image: redis
  cpu_shares: 100
  mem_limit: 262144000